name: quote_generator_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bs4
  - pandas
  - openpyxl
  - xlsxwriter
  - requests
  - jupyter
  - jupyterlab
  - loguru
  - nbformat
  - nb_conda_kernels
  - xlrd
  - lxml
  - tqdm
  - python-dotenv
  - pip 
  - pip:
    - pillow
    